### ISSUE TITLE
Documentation: direct download link does not work

### ISSUE THREAD

**Issue by rvaheldendaten** [stefanwalther/sense-on-off-switch#2]
hi stefan!

just a small one: your documentation point to the downloadlink https://github.com/stefanwalther/sense-on-off-switch/raw/master/build/swr-on-off-switch_latest.zip

--> normal download works fine, but the link in the documentation seems to be outdated
--> I get a 404 for this page;

**Comment by stefanwalther** [comment]
Thx for reporting, will fix.
